export const USERS_MUTATION_RATE_LIMIT_MAX_ATTEMPTS = 10;
export const USERS_MUTATION_RATE_LIMIT_WINDOW_MS = 15 * 60 * 1000;

export const USERS_READ_RATE_LIMIT_MAX_ATTEMPTS = 120;
export const USERS_READ_RATE_LIMIT_WINDOW_MS = 60 * 1000;
